import { defineStageLayout, type StageLayoutConfig } from "./stageTypes";
import type { StageSpawnZoneConfig } from "./stageSpawnTypes";
import { createStageVisualProfile } from "./stageVisualPresets";

export const market95Layout: StageLayoutConfig = defineStageLayout({
  stageId: "market_95",
  displayName: "MERCADO 95",
  tileSize: 32,
  mapWidthTiles: 80,
  mapHeightTiles: 8,
  sourceTilesPerRow: 20,
  tilesetKey: "street_market_tileset",
  cameraYOffset: 0,
  walkRails: [
    { id: "rail_west", xStart: 0, xEnd: 820, topY: 182, bottomY: 226, preferredY: 204 },
    { id: "rail_mid", xStart: 820, xEnd: 1660, topY: 186, bottomY: 230, preferredY: 208 },
    { id: "rail_east", xStart: 1660, xEnd: 2560, topY: 180, bottomY: 226, preferredY: 203 },
  ],
  layers: [
    { id: "facade", depth: 12, alpha: 1, targetRows: [1, 2, 3], sourceRows: [0, 1, 1] },
    { id: "sidewalk", depth: 18, alpha: 1, targetRows: [4], sourceRows: [10] },
    { id: "road", depth: 24, alpha: 1, targetRows: [5, 6], sourceRows: [11, 11] },
    { id: "foreground_deco", depth: 520, alpha: 0.98, targetRows: [7], sourceRows: [9] },
  ],
  objects: [
    {
      id: "stall_entry",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.82,
        tint: 0xb6c2e8,
      },
      transform: {
        x: 236,
        y: 212,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 220,
        depthOffset: 0,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "booth_a",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
      },
      transform: {
        x: 574,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 228,
        depthOffset: 0,
      },
      collision: {
        blocksMovement: true,
        color: 0x00c5ff,
        footprint: {
          mode: "explicit",
          width: 58,
          height: 14,
        },
      },
      behavior: { type: "static" },
    },
    {
      id: "produce_dump",
      visual: {
        textureKey: "prop_dumpster_open",
        scaleTier: "compact",
        spriteSpecId: "stage_prop_arcade",
        scaleOverride: 0.3,
        tint: 0x7b8d3a,
      },
      transform: {
        x: 1034,
        y: 222,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 226,
        depthOffset: 2,
      },
      collision: {
        blocksMovement: true,
        color: 0xff9b43,
        footprint: {
          mode: "explicit",
          width: 92,
          height: 18,
        },
      },
      behavior: { type: "static" },
    },
    {
      id: "crate_1",
      visual: {
        textureKey: "prop_crate",
        scaleTier: "tiny",
        spriteSpecId: "stage_breakable_arcade",
      },
      transform: {
        x: 782,
        y: 220,
        originX: 0.5,
        originY: 1,
      },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: {
          mode: "rule",
          rule: "sprite_base_band",
          widthRatio: 0.58,
          minWidth: 18,
          maxWidthRatio: 1,
          height: 14,
          baselineOffset: 7,
        },
      },
      behavior: {
        type: "breakable",
        maxHp: 26,
        points: 120,
        drop: { type: "small_heal", chance: 1, healAmount: 26 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "stall_mid",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.9,
        tint: 0xcfd5ef,
      },
      transform: {
        x: 1286,
        y: 214,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 220,
        depthOffset: 0,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "market_sign_left",
      visual: {
        textureKey: "prop_sign_post",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.92,
        tint: 0xffc35e,
      },
      transform: {
        x: 344,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "market_bin_mid",
      visual: {
        textureKey: "prop_trash_bin_small",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.9,
        tint: 0xd3d9dd,
      },
      transform: {
        x: 872,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "market_tree_mid",
      visual: {
        textureKey: "prop_street_tree",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.72,
      },
      transform: {
        x: 1148,
        y: 212,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 216,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "market_cone_right",
      visual: {
        textureKey: "prop_caution_cone",
        scaleTier: "hero",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.94,
      },
      transform: {
        x: 1522,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "crate_2",
      visual: {
        textureKey: "prop_crate",
        scaleTier: "tiny",
        spriteSpecId: "stage_breakable_arcade",
      },
      transform: {
        x: 1492,
        y: 220,
        originX: 0.5,
        originY: 1,
      },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: {
          mode: "rule",
          rule: "sprite_base_band",
          widthRatio: 0.58,
          minWidth: 18,
          maxWidthRatio: 1,
          height: 14,
          baselineOffset: 7,
        },
      },
      behavior: {
        type: "breakable",
        maxHp: 26,
        points: 120,
        drop: { type: "medium_heal", chance: 0.8, healAmount: 40 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "crate_3",
      visual: {
        textureKey: "prop_crate",
        scaleTier: "tiny",
        spriteSpecId: "stage_breakable_arcade",
      },
      transform: {
        x: 438,
        y: 220,
        originX: 0.5,
        originY: 1,
      },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: {
          mode: "rule",
          rule: "sprite_base_band",
          widthRatio: 0.58,
          minWidth: 18,
          maxWidthRatio: 1,
          height: 14,
          baselineOffset: 7,
        },
      },
      behavior: {
        type: "breakable",
        maxHp: 24,
        points: 110,
        drop: { type: "small_heal", chance: 0.75, healAmount: 24 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "crate_4",
      visual: {
        textureKey: "prop_crate",
        scaleTier: "tiny",
        spriteSpecId: "stage_breakable_arcade",
      },
      transform: {
        x: 1168,
        y: 220,
        originX: 0.5,
        originY: 1,
      },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: {
          mode: "rule",
          rule: "sprite_base_band",
          widthRatio: 0.58,
          minWidth: 18,
          maxWidthRatio: 1,
          height: 14,
          baselineOffset: 7,
        },
      },
      behavior: {
        type: "breakable",
        maxHp: 24,
        points: 110,
        drop: { type: "small_heal", chance: 0.8, healAmount: 24 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "booth_exit",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.82,
        tint: 0x9da7c5,
      },
      transform: {
        x: 1988,
        y: 212,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 220,
        depthOffset: 0,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "market_sign_mid",
      visual: {
        textureKey: "prop_sign_post",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.9,
        tint: 0x7ce0ff,
      },
      transform: {
        x: 1020,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "market_bin_right",
      visual: {
        textureKey: "prop_trash_bin_small",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.88,
        tint: 0xc8d0d4,
      },
      transform: {
        x: 1668,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "market_barricade_mid",
      visual: {
        textureKey: "prop_barricade_small",
        scaleTier: "hero",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.86,
        tint: 0xffd86a,
      },
      transform: {
        x: 1408,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
  ],
  parallaxBands: [
    { id: "skyline_far", textureKey: "oga_urban_sky", y: 0, height: 82, depth: 2, alpha: 0.42, scrollFactor: 0.02, tileScale: 3 },
    { id: "skyline_mid", textureKey: "oga_city_bg", y: 30, height: 86, depth: 3, alpha: 0.5, scrollFactor: 0.08, tileScale: 3 },
    { id: "skyline_close", textureKey: "oga_urban_buildings", y: 62, height: 116, depth: 4, alpha: 0.74, scrollFactor: 0.16, tileScale: 3 },
  ],
  neonLabels: [
    { x: 184, y: 64, text: "MERCADO SUR", color: "#ff5e53", fontSize: "14px" },
    { x: 706, y: 82, text: "OFERTA BRAVA", color: "#ffbf47", fontSize: "10px" },
    { x: 1310, y: 74, text: "BODEGA 24H", color: "#7ce0ff", fontSize: "10px" },
    { x: 1896, y: 70, text: "SIN FIAR", color: "#ff6db6", fontSize: "10px" },
  ],
  visualProfile: createStageVisualProfile("industrialWarm", {
    rainIntensity: 0.08,
    rainDriftSpeed: 0.34,
    fogAlpha: 0.03,
    neonIntensity: 0.88,
    neonPulseHz: 1.25,
    colorGrade: { color: 0x29110b, alpha: 0.06 },
  }),
});

export const market95Spawns: StageSpawnZoneConfig[] = [
  {
    id: "market_zone_1",
    triggerX: 340,
    lockType: "full_lock",
    objective: {
      type: "clear_all",
    },
    reinforcementPolicy: "none",
    leftBarrierX: 92,
    rightBarrierX: 880,
    spawns: [
      { x: 620, y: 204, archetype: "brawler" },
      { x: 792, y: 198, archetype: "knife_fighter" },
    ],
  },
  {
    id: "market_zone_2",
    triggerX: 1060,
    lockType: "partial_lock",
    objective: {
      type: "break_cache",
      cacheObjectIds: ["crate_2", "crate_4"],
    },
    reinforcementPolicy: "staggered",
    barrier: {
      openRailIds: ["rail_mid"],
    },
    leftBarrierX: 1020,
    rightBarrierX: 1710,
    spawns: [
      { x: 1310, y: 208, archetype: "brawler" },
      { x: 1450, y: 194, archetype: "rusher" },
      { x: 1600, y: 210, archetype: "knife_fighter" },
    ],
  },
];
