import { defineStageLayout, type StageLayoutConfig } from "./stageTypes";
import type { StageSpawnZoneConfig } from "./stageSpawnTypes";
import { createStageVisualProfile } from "./stageVisualPresets";

export const metroSurLayout: StageLayoutConfig = defineStageLayout({
  stageId: "metro_sur",
  displayName: "METRO SUR",
  tileSize: 32,
  mapWidthTiles: 80,
  mapHeightTiles: 8,
  sourceTilesPerRow: 20,
  tilesetKey: "street_metro_tileset",
  cameraYOffset: 0,
  walkRails: [
    { id: "rail_west", xStart: 0, xEnd: 860, topY: 176, bottomY: 216, preferredY: 198 },
    { id: "rail_mid", xStart: 860, xEnd: 1640, topY: 180, bottomY: 220, preferredY: 202 },
    { id: "rail_east", xStart: 1640, xEnd: 2560, topY: 174, bottomY: 216, preferredY: 197 },
  ],
  layers: [
    { id: "facade", depth: 86, alpha: 0.98, targetRows: [0, 1, 2, 3], sourceRows: [0, 1, 2, 2] },
    { id: "sidewalk", depth: 94, alpha: 1, targetRows: [4], sourceRows: [10] },
    { id: "road", depth: 108, alpha: 1, targetRows: [5, 6], sourceRows: [11, 11] },
    { id: "foreground_deco", depth: 248, alpha: 0.96, targetRows: [7], sourceRows: [9] },
  ],
  objects: [
    {
      id: "platform_booth_left",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.74,
        tint: 0x8a99b8,
      },
      transform: {
        x: 212,
        y: 210,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 216,
        depthOffset: 0,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "booth_ticket",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
      },
      transform: {
        x: 604,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 226,
        depthOffset: 0,
      },
      collision: {
        blocksMovement: true,
        color: 0x66d1ff,
        footprint: {
          mode: "explicit",
          width: 58,
          height: 14,
        },
      },
      behavior: { type: "static" },
    },
    {
      id: "service_pair",
      visual: {
        textureKey: "prop_container_pair",
        scaleTier: "compact",
        spriteSpecId: "stage_prop_arcade",
        scaleOverride: 0.3,
        tint: 0x5d7f56,
      },
      transform: {
        x: 984,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 224,
        depthOffset: 2,
      },
      collision: {
        blocksMovement: true,
        color: 0xff7e98,
        footprint: {
          mode: "explicit",
          width: 92,
          height: 18,
        },
      },
      behavior: { type: "static" },
    },
    {
      id: "service_box",
      visual: {
        textureKey: "prop_container",
        scaleTier: "compact",
        spriteSpecId: "stage_prop_arcade",
        scaleOverride: 0.3,
        alpha: 0.84,
        tint: 0x5a7350,
      },
      transform: {
        x: 1532,
        y: 218,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 220,
        depthOffset: 2,
      },
      collision: {
        blocksMovement: true,
        color: 0xdca15d,
        footprint: {
          mode: "explicit",
          width: 66,
          height: 16,
        },
      },
      behavior: { type: "static" },
    },
    {
      id: "platform_booth_right",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.68,
        tint: 0x7785a1,
      },
      transform: {
        x: 1932,
        y: 208,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 214,
        depthOffset: 0,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "metro_sign_left",
      visual: {
        textureKey: "prop_sign_post",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.94,
        tint: 0xffd86a,
      },
      transform: {
        x: 418,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "metro_bin_mid",
      visual: {
        textureKey: "prop_trash_bin_small",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.92,
        tint: 0xa7b5c4,
      },
      transform: {
        x: 1172,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "metro_cone_mid",
      visual: {
        textureKey: "prop_caution_cone",
        scaleTier: "hero",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.96,
      },
      transform: {
        x: 1384,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "metro_barricade_right",
      visual: {
        textureKey: "prop_barricade_small",
        scaleTier: "hero",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.88,
      },
      transform: {
        x: 1788,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "metro_sign_mid",
      visual: {
        textureKey: "prop_sign_post",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.92,
        tint: 0x8fa8ff,
      },
      transform: {
        x: 842,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "metro_bin_right",
      visual: {
        textureKey: "prop_trash_bin_small",
        scaleTier: "large",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.9,
        tint: 0xb5bec9,
      },
      transform: {
        x: 1678,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "metro_barricade_mid",
      visual: {
        textureKey: "prop_barricade_small",
        scaleTier: "hero",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.9,
        tint: 0xffd86a,
      },
      transform: {
        x: 1490,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 222,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "barrel_1",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade" },
      transform: { x: 902, y: 220, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 30,
        points: 160,
        drop: { type: "small_heal", chance: 1, healAmount: 30 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "barrel_2",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade" },
      transform: { x: 1362, y: 220, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 30,
        points: 160,
        drop: { type: "medium_heal", chance: 0.9, healAmount: 46 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "barrel_3",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade" },
      transform: { x: 534, y: 220, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 28,
        points: 140,
        drop: { type: "small_heal", chance: 0.82, healAmount: 28 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "barrel_4",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade" },
      transform: { x: 1946, y: 220, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 28,
        points: 140,
        drop: { type: "small_heal", chance: 0.85, healAmount: 30 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
  ],
  parallaxBands: [
    { id: "skyline_far", textureKey: "oga_urban_sky", y: 0, height: 88, depth: 2, alpha: 0.48, scrollFactor: 0.03, tileScale: 3 },
    { id: "skyline_mid", textureKey: "oga_urban_buildings", y: 22, height: 102, depth: 3, alpha: 0.68, scrollFactor: 0.12, tileScale: 3 },
    { id: "skyline_close", textureKey: "city_close_metro_band", y: 64, height: 126, depth: 4, alpha: 0.86, scrollFactor: 0.26, tileScale: 1 },
  ],
  neonLabels: [
    { x: 226, y: 54, text: "METRO SUR", color: "#6de4ff", fontSize: "14px" },
    { x: 920, y: 62, text: "ULTIMO TREN", color: "#ffd86a", fontSize: "10px" },
    { x: 1464, y: 66, text: "SALIDA 6", color: "#ff6798", fontSize: "10px" },
    { x: 2004, y: 58, text: "ANDEN CERRADO", color: "#8fa8ff", fontSize: "10px" },
  ],
  visualProfile: createStageVisualProfile("wetNight", {
    rainIntensity: 0.94,
    rainDriftSpeed: 1,
    fogAlpha: 0.07,
    neonIntensity: 0.96,
    neonPulseHz: 1.65,
    colorGrade: { color: 0x101724, alpha: 0.08 },
  }),
});

export const metroSurSpawns: StageSpawnZoneConfig[] = [
  {
    id: "metro_zone_1",
    triggerX: 360,
    lockType: "full_lock",
    objective: {
      type: "hold_line",
      holdDurationSec: 20,
    },
    reinforcementPolicy: "staggered",
    leftBarrierX: 108,
    rightBarrierX: 920,
    spawns: [
      { x: 620, y: 210, archetype: "brawler" },
      { x: 760, y: 200, archetype: "rusher" },
      { x: 870, y: 210, archetype: "rusher" },
    ],
  },
  {
    id: "metro_zone_2",
    triggerX: 1180,
    lockType: "partial_lock",
    objective: {
      type: "clear_all",
    },
    reinforcementPolicy: "burst",
    barrier: {
      openRailIds: ["rail_west"],
    },
    leftBarrierX: 1140,
    rightBarrierX: 1820,
    spawns: [
      { x: 1380, y: 212, archetype: "brawler" },
      { x: 1530, y: 198, archetype: "agile_f" },
      { x: 1680, y: 208, archetype: "bat_wielder" },
    ],
  },
];
