import { defineStageLayout, type StageLayoutConfig } from "./stageTypes";
import type { StageSpawnZoneConfig } from "./stageSpawnTypes";
import { createStageVisualProfile } from "./stageVisualPresets";

export const playaNocheLayout: StageLayoutConfig = defineStageLayout({
  stageId: "playa_noche",
  displayName: "PLAYA NOCHE",
  tileSize: 32,
  mapWidthTiles: 80,
  mapHeightTiles: 8,
  sourceTilesPerRow: 20,
  tilesetKey: "street_playa_tileset",
  cameraYOffset: -6,
  walkRails: [
    { id: "rail_west", xStart: 0, xEnd: 900, topY: 184, bottomY: 228, preferredY: 206 },
    { id: "rail_mid", xStart: 900, xEnd: 1700, topY: 188, bottomY: 232, preferredY: 210 },
    { id: "rail_east", xStart: 1700, xEnd: 2560, topY: 182, bottomY: 226, preferredY: 205 },
  ],
  layers: [
    { id: "facade", depth: 76, alpha: 0.8, targetRows: [2, 3], sourceRows: [1, 0] },
    { id: "sidewalk", depth: 88, alpha: 0.9, targetRows: [4], sourceRows: [10] },
    { id: "road", depth: 100, alpha: 0.94, targetRows: [5, 6], sourceRows: [11, 11] },
    { id: "foreground_deco", depth: 240, alpha: 0.82, targetRows: [7], sourceRows: [9] },
  ],
  objects: [
    {
      id: "booth_shack_left",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.7,
        tint: 0x7c9eb2,
      },
      transform: {
        x: 492,
        y: 212,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 216,
        depthOffset: 0,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "booth_beach",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        tint: 0x8cb9d2,
      },
      transform: {
        x: 918,
        y: 218,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 224,
        depthOffset: 0,
      },
      collision: {
        blocksMovement: true,
        color: 0x74dcff,
        footprint: {
          mode: "explicit",
          width: 58,
          height: 14,
        },
      },
      behavior: { type: "static" },
    },
    {
      id: "booth_boardwalk",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.76,
        tint: 0x668aa4,
      },
      transform: {
        x: 1688,
        y: 210,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 216,
        depthOffset: 0,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "table_1",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade", tint: 0x7da3a0 },
      transform: { x: 646, y: 216, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 24,
        points: 150,
        drop: { type: "small_heal", chance: 1, healAmount: 34 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0x94b9b0,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "table_2",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade", tint: 0x7da3a0 },
      transform: { x: 1286, y: 216, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 24,
        points: 150,
        drop: { type: "medium_heal", chance: 0.95, healAmount: 52 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0x94b9b0,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "table_3",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade", tint: 0x7da3a0 },
      transform: { x: 380, y: 216, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 22,
        points: 130,
        drop: { type: "small_heal", chance: 0.78, healAmount: 28 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0x94b9b0,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "table_4",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade", tint: 0x7da3a0 },
      transform: { x: 1848, y: 216, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 22,
        points: 130,
        drop: { type: "small_heal", chance: 0.82, healAmount: 30 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0x94b9b0,
        hitTint: 0xffd2d2,
      },
    },
  ],
  parallaxBands: [
    { id: "skyline_far", textureKey: "city_far_playa_band", y: 22, height: 56, depth: 2, alpha: 0.3, scrollFactor: 0.02, tileScale: 0.38 },
    { id: "skyline_mid", textureKey: "city_mid_playa_band", y: 56, height: 72, depth: 3, alpha: 0.42, scrollFactor: 0.07, tileScale: 0.48 },
    { id: "skyline_close", textureKey: "city_close_playa_band", y: 102, height: 92, depth: 4, alpha: 0.58, scrollFactor: 0.12, tileScale: 0.58 },
  ],
  neonLabels: [
    { x: 196, y: 58, text: "MALECON", color: "#ff73bf", fontSize: "14px" },
    { x: 900, y: 92, text: "CHIRINGUITO", color: "#8de8ff", fontSize: "10px" },
    { x: 1484, y: 74, text: "RUTA NORTE", color: "#ffe773", fontSize: "10px" },
    { x: 1986, y: 64, text: "PLAYA ABIERTA", color: "#6fe3ff", fontSize: "10px" },
  ],
  visualProfile: createStageVisualProfile("neonCoast", {
    rainIntensity: 0,
    fogAlpha: 0.02,
    neonIntensity: 0.96,
    neonPulseHz: 1.8,
    colorGrade: { color: 0x0e2130, alpha: 0.06 },
    foregroundAccents: {
      skylineFar: 0x3d6691,
      skylineMid: 0x4d7ea2,
      skylineClose: 0x6b9cc0,
      facade: 0x88a5b6,
      foregroundDeco: 0x5f8ca4,
      crateTint: 0x6a8f8c,
      crateAlpha: 0.8,
    },
  }),
});

export const playaNocheSpawns: StageSpawnZoneConfig[] = [
  {
    id: "playa_zone_1",
    triggerX: 360,
    lockType: "full_lock",
    objective: {
      type: "clear_all",
    },
    reinforcementPolicy: "burst",
    barrier: {
      topGap: 54,
      bottomGap: 126,
    },
    leftBarrierX: 104,
    rightBarrierX: 930,
    spawns: [
      { x: 600, y: 206, archetype: "brawler" },
      { x: 730, y: 194, archetype: "rusher" },
      { x: 840, y: 210, archetype: "agile_f" },
      { x: 900, y: 200, archetype: "bat_wielder" },
    ],
  },
  {
    id: "playa_zone_2",
    triggerX: 1160,
    lockType: "soft_lock",
    objective: {
      type: "hold_line",
      holdDurationSec: 24,
    },
    reinforcementPolicy: "staggered",
    leftBarrierX: 1120,
    rightBarrierX: 1840,
    spawns: [
      { x: 1360, y: 212, archetype: "rusher" },
      { x: 1500, y: 198, archetype: "agile_f" },
      { x: 1620, y: 206, archetype: "bat_wielder" },
      { x: 1760, y: 208, archetype: "brawler" },
    ],
  },
];
