import { defineStageLayout, type StageLayoutConfig } from "./stageTypes";
import type { StageSpawnZoneConfig } from "./stageSpawnTypes";
import { createStageVisualProfile } from "./stageVisualPresets";

export const puertoRojoLayout: StageLayoutConfig = defineStageLayout({
  stageId: "puerto_rojo",
  displayName: "PUERTO ROJO",
  tileSize: 32,
  mapWidthTiles: 80,
  mapHeightTiles: 8,
  sourceTilesPerRow: 20,
  tilesetKey: "street_puerto_tileset",
  cameraYOffset: 0,
  walkRails: [
    { id: "rail_west", xStart: 0, xEnd: 860, topY: 178, bottomY: 220, preferredY: 200 },
    { id: "rail_mid", xStart: 860, xEnd: 1640, topY: 182, bottomY: 224, preferredY: 204 },
    { id: "rail_east", xStart: 1640, xEnd: 2560, topY: 176, bottomY: 220, preferredY: 199 },
  ],
  layers: [
    { id: "facade", depth: 84, alpha: 0.98, targetRows: [1, 2, 3], sourceRows: [2, 1, 0] },
    { id: "sidewalk", depth: 94, alpha: 1, targetRows: [4], sourceRows: [10] },
    { id: "road", depth: 108, alpha: 1, targetRows: [5, 6], sourceRows: [11, 11] },
    { id: "foreground_deco", depth: 252, alpha: 0.98, targetRows: [7], sourceRows: [9] },
  ],
  objects: [
    {
      id: "dock_dump",
      visual: {
        textureKey: "prop_dumpster_open",
        scaleTier: "compact",
        spriteSpecId: "stage_prop_arcade",
        scaleOverride: 0.3,
        tint: 0x6d7d37,
      },
      transform: {
        x: 512,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 224,
        depthOffset: 2,
      },
      collision: {
        blocksMovement: true,
        color: 0x65d9ff,
        footprint: {
          mode: "explicit",
          width: 92,
          height: 18,
        },
      },
      behavior: { type: "static" },
    },
    {
      id: "booth_harbor",
      visual: {
        textureKey: "prop_booth_front",
        scaleTier: "tiny",
        spriteSpecId: "stage_prop_arcade",
        alpha: 0.78,
        tint: 0xa3b0cb,
      },
      transform: {
        x: 760,
        y: 212,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 216,
        depthOffset: 0,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "container_harbor",
      visual: {
        textureKey: "prop_container",
        scaleTier: "compact",
        spriteSpecId: "stage_prop_arcade",
        scaleOverride: 0.3,
        tint: 0x5f7c53,
      },
      transform: {
        x: 1088,
        y: 220,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 224,
        depthOffset: 2,
      },
      collision: {
        blocksMovement: true,
        color: 0xff7998,
        footprint: {
          mode: "explicit",
          width: 68,
          height: 16,
        },
      },
      behavior: { type: "static" },
    },
    {
      id: "container_stack_mid",
      visual: {
        textureKey: "prop_container_pair",
        scaleTier: "compact",
        spriteSpecId: "stage_prop_arcade",
        scaleOverride: 0.3,
        tint: 0x61744d,
      },
      transform: {
        x: 1502,
        y: 216,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 220,
        depthOffset: 2,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "container_stack_far",
      visual: {
        textureKey: "prop_container_pair",
        scaleTier: "compact",
        spriteSpecId: "stage_prop_arcade",
        scaleOverride: 0.3,
        alpha: 0.74,
        tint: 0x4b5b43,
      },
      transform: {
        x: 2028,
        y: 208,
        originX: 0.5,
        originY: 1,
        depthAnchorY: 214,
        depthOffset: 2,
      },
      behavior: { type: "decorative" },
    },
    {
      id: "crate_final_1",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade" },
      transform: { x: 842, y: 220, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 28,
        points: 180,
        drop: { type: "small_heal", chance: 1, healAmount: 38 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "crate_final_2",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade" },
      transform: { x: 1836, y: 220, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 28,
        points: 180,
        drop: { type: "medium_heal", chance: 1, healAmount: 58 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "crate_final_3",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade" },
      transform: { x: 1268, y: 220, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 26,
        points: 160,
        drop: { type: "small_heal", chance: 0.86, healAmount: 34 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
    {
      id: "crate_final_4",
      visual: { textureKey: "prop_crate", scaleTier: "tiny", spriteSpecId: "stage_breakable_arcade" },
      transform: { x: 1582, y: 220, originX: 0.5, originY: 1 },
      collision: {
        blocksMovement: true,
        color: 0xffcc66,
        footprint: { mode: "rule", rule: "sprite_base_band", widthRatio: 0.58, minWidth: 18, maxWidthRatio: 1, height: 14, baselineOffset: 7 },
      },
      behavior: {
        type: "breakable",
        maxHp: 26,
        points: 160,
        drop: { type: "small_heal", chance: 0.9, healAmount: 36 },
        hurtbox: { mode: "rule", rule: "sprite_bounds" },
        intactTint: 0xb8c7d2,
        hitTint: 0xffd2d2,
      },
    },
  ],
  parallaxBands: [
    { id: "skyline_far", textureKey: "oga_industrial_bg", y: 0, height: 90, depth: 2, alpha: 0.44, scrollFactor: 0.02, tileScale: 3 },
    { id: "skyline_mid", textureKey: "oga_industrial_far", y: 24, height: 108, depth: 3, alpha: 0.58, scrollFactor: 0.09, tileScale: 3 },
    { id: "skyline_close", textureKey: "oga_industrial_buildings", y: 62, height: 134, depth: 4, alpha: 0.84, scrollFactor: 0.18, tileScale: 3 },
  ],
  neonLabels: [
    { x: 190, y: 62, text: "PUERTO ROJO", color: "#ff6a7c", fontSize: "14px" },
    { x: 986, y: 74, text: "MUELLE 9", color: "#6ed7ff", fontSize: "10px" },
    { x: 1466, y: 68, text: "ZONA DE CARGA", color: "#ffe280", fontSize: "10px" },
    { x: 2058, y: 56, text: "LOS GRISES", color: "#ff7fc3", fontSize: "10px" },
  ],
  visualProfile: createStageVisualProfile("crimsonHarbor", {
    rainIntensity: 0.76,
    rainDriftSpeed: 0.74,
    fogAlpha: 0.04,
    neonIntensity: 0.9,
    neonPulseHz: 1.28,
    colorGrade: { color: 0x251018, alpha: 0.08 },
  }),
});

export const puertoRojoSpawns: StageSpawnZoneConfig[] = [
  {
    id: "puerto_zone_1",
    triggerX: 360,
    lockType: "full_lock",
    objective: {
      type: "break_cache",
      cacheObjectIds: ["crate_final_1", "crate_final_3"],
    },
    reinforcementPolicy: "staggered",
    leftBarrierX: 108,
    rightBarrierX: 920,
    spawns: [
      { x: 620, y: 210, archetype: "brawler" },
      { x: 730, y: 198, archetype: "rusher" },
      { x: 820, y: 206, archetype: "agile_f" },
      { x: 900, y: 198, archetype: "bat_wielder" },
    ],
  },
  {
    id: "puerto_zone_2",
    triggerX: 1180,
    lockType: "partial_lock",
    objective: {
      type: "clear_all",
    },
    reinforcementPolicy: "burst",
    barrier: {
      openRailIds: ["rail_east"],
    },
    leftBarrierX: 1140,
    rightBarrierX: 1880,
    spawns: [
      { x: 1360, y: 212, archetype: "rusher" },
      { x: 1480, y: 198, archetype: "brawler" },
      { x: 1600, y: 208, archetype: "agile_f" },
      { x: 1700, y: 206, archetype: "bat_wielder" },
      { x: 1780, y: 208, archetype: "brawler" },
      { x: 1840, y: 206, archetype: "mini_boss" },
    ],
  },
];
