import type { AssetManifestEntry } from "../assetTypes";
import { localAsset } from "../assetTypes";

function createArcadeCharacterSet(prefix: "player" | "enemy"): AssetManifestEntry[] {
  const packId = "arcade_90" as const;
  const author = "Spain 90 Team";
  const basePath = `arcade/sprites/${prefix}`;
  const clipKeys = [
    "idle_strip10",
    "walk_strip10",
    "attack1_strip10",
    "attack2_strip10",
    "attack3_strip10",
    "air_attack_strip10",
    "special_strip10",
    "hurt_strip10",
    "knockdown_strip10",
    "getup_strip10",
  ] as const;

  return clipKeys.map((clip) => ({
    key: `${prefix}_${clip}`,
    path: localAsset(`${basePath}_${clip}.png`),
    type: "spritesheet",
    role: "character",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author,
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "arcade-cps-inspired",
    scaleProfile: "fighter-64x128",
    packId,
    tags: ["fighter", "arcade", clip],
    frameConfig: {
      frameWidth: 64,
      frameHeight: 128,
    },
  }));
}

const ARCADE_COMMON: AssetManifestEntry[] = [
  {
    key: "street_sheet",
    path: localAsset("arcade/sprites/street_sheet.png"),
    type: "image",
    role: "tileset",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "arcade-cps-inspired",
    scaleProfile: "bg-arcade",
    packId: "arcade_90",
    tags: ["stage", "arcade"],
  },
  {
    key: "street_tileset",
    path: localAsset("arcade/sprites/street_tileset.png"),
    type: "image",
    role: "tileset",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "arcade-cps-inspired",
    scaleProfile: "tile-32x32",
    packId: "arcade_90",
    tags: ["stage", "arcade"],
  },
  {
    key: "street_props",
    path: localAsset("arcade/sprites/street_props.png"),
    type: "image",
    role: "prop",
    critical: false,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "arcade-cps-inspired",
    scaleProfile: "prop-arcade",
    packId: "arcade_90",
    tags: ["prop", "arcade"],
  },
  {
    key: "police_car_sheet",
    path: localAsset("arcade/sprites/police_car_sheet.png"),
    type: "image",
    role: "prop",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "arcade-cps-inspired",
    scaleProfile: "prop-arcade",
    packId: "arcade_90",
    tags: ["prop", "arcade"],
  },
  {
    key: "city_far",
    path: localAsset("arcade/backgrounds/city_far.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "blue-night-arcade",
    scaleProfile: "bg-wide",
    packId: "arcade_90",
    tags: ["background", "arcade"],
  },
  {
    key: "city_mid",
    path: localAsset("arcade/backgrounds/city_mid.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "blue-night-arcade",
    scaleProfile: "bg-wide",
    packId: "arcade_90",
    tags: ["background", "arcade"],
  },
  {
    key: "city_close",
    path: localAsset("arcade/backgrounds/city_close.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "blue-night-arcade",
    scaleProfile: "bg-wide",
    packId: "arcade_90",
    tags: ["background", "arcade"],
  },
  {
    key: "portrait_boxeador",
    path: localAsset("arcade/ui/portrait_boxeador.png"),
    type: "image",
    role: "ui",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "arcade-cps-inspired",
    scaleProfile: "portrait-48",
    packId: "arcade_90",
    tags: ["ui", "portrait", "arcade"],
  },
  {
    key: "portrait_veloz",
    path: localAsset("arcade/ui/portrait_veloz.png"),
    type: "image",
    role: "ui",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "arcade-cps-inspired",
    scaleProfile: "portrait-48",
    packId: "arcade_90",
    tags: ["ui", "portrait", "arcade"],
  },
  {
    key: "portrait_tecnico",
    path: localAsset("arcade/ui/portrait_tecnico.png"),
    type: "image",
    role: "ui",
    critical: true,
    pixelScale: 1,
    source: "Original",
    author: "Spain 90 Team",
    license: "CC0",
    url: "https://iv-beat.netlify.app/",
    paletteProfile: "arcade-cps-inspired",
    scaleProfile: "portrait-48",
    packId: "arcade_90",
    tags: ["ui", "portrait", "arcade"],
  },
  {
    key: "theme_a",
    path: localAsset("arcade/audio/theme_a.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "bart",
    license: "CC0",
    url: "https://opengameart.org/content/spacyloop",
    paletteProfile: "arcade-90s",
    scaleProfile: "audio-loop",
    packId: "arcade_90",
    tags: ["audio", "theme"],
  },
  {
    key: "theme_b",
    path: localAsset("arcade/audio/theme_b.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Binarpilot",
    license: "CC0",
    url: "https://opengameart.org/content/empty-city",
    paletteProfile: "arcade-90s",
    scaleProfile: "audio-loop",
    packId: "arcade_90",
    tags: ["audio", "theme"],
  },
  {
    key: "sfx_hit",
    path: localAsset("arcade/audio/sfx_hit.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Devlos",
    license: "CC-BY",
    url: "https://opengameart.org/content/punch-sound-effect",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "arcade_90",
    tags: ["audio", "sfx", "hit"],
  },
  {
    key: "sfx_hit_alt",
    path: localAsset("arcade/audio/sfx_hit_alt.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Devlos",
    license: "CC-BY",
    url: "https://opengameart.org/content/punch-sound-effect",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "arcade_90",
    tags: ["audio", "sfx", "hit"],
  },
  {
    key: "sfx_jump",
    path: localAsset("arcade/audio/sfx_jump.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC-BY",
    url: "https://opengameart.org/content/jump-and-run-8-bit",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "arcade_90",
    tags: ["audio", "sfx", "jump"],
  },
  {
    key: "sfx_special",
    path: localAsset("arcade/audio/sfx_special.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "arcade_90",
    tags: ["audio", "sfx", "special"],
  },
  {
    key: "sfx_knockdown",
    path: localAsset("arcade/audio/sfx_knockdown.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "arcade_90",
    tags: ["audio", "sfx", "knockdown"],
  },
  {
    key: "sfx_break",
    path: localAsset("arcade/audio/sfx_break.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "arcade_90",
    tags: ["audio", "sfx", "break"],
  },
  {
    key: "sfx_ui",
    path: localAsset("arcade/audio/sfx_ui.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "arcade_90",
    tags: ["audio", "sfx", "ui"],
  },
];

export const arcadeManifest: AssetManifestEntry[] = [
  ...createArcadeCharacterSet("player"),
  ...createArcadeCharacterSet("enemy"),
  ...ARCADE_COMMON,
];
