import type { AssetManifestEntry } from "../assetTypes";
import { localAsset } from "../assetTypes";

function createLegacyCharacterSet(prefix: "player" | "enemy", url: string): AssetManifestEntry[] {
  const author = "chasersgaming";
  const paletteProfile = "sms-nocturno-neon";
  const packId = "legacy_sms" as const;
  return [
    {
      key: `${prefix}_idle_strip4`,
      path: localAsset(`sprites/${prefix}_idle_strip4.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16x32",
      packId,
      tags: ["fighter", "idle", "legacy"],
      frameConfig: { frameWidth: 16, frameHeight: 32 },
    },
    {
      key: `${prefix}_walk_strip4`,
      path: localAsset(`sprites/${prefix}_walk_strip4.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16x32",
      packId,
      tags: ["fighter", "walk", "legacy"],
      frameConfig: { frameWidth: 16, frameHeight: 32 },
    },
    {
      key: `${prefix}_punch1`,
      path: localAsset(`sprites/${prefix}_punch1.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-24x32",
      packId,
      tags: ["fighter", "attack", "legacy"],
      frameConfig: { frameWidth: 24, frameHeight: 32 },
    },
    {
      key: `${prefix}_punch2`,
      path: localAsset(`sprites/${prefix}_punch2.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-24x32",
      packId,
      tags: ["fighter", "attack", "legacy"],
      frameConfig: { frameWidth: 24, frameHeight: 32 },
    },
    {
      key: `${prefix}_kick1`,
      path: localAsset(`sprites/${prefix}_kick1.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-24x32",
      packId,
      tags: ["fighter", "attack", "legacy"],
      frameConfig: { frameWidth: 24, frameHeight: 32 },
    },
    {
      key: `${prefix}_kick2`,
      path: localAsset(`sprites/${prefix}_kick2.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-24x32",
      packId,
      tags: ["fighter", "attack", "legacy"],
      frameConfig: { frameWidth: 24, frameHeight: 32 },
    },
    {
      key: `${prefix}_hurt`,
      path: localAsset(`sprites/${prefix}_hurt.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16x32",
      packId,
      tags: ["fighter", "hurt", "legacy"],
      frameConfig: { frameWidth: 16, frameHeight: 32 },
    },
    {
      key: `${prefix}_knockdown`,
      path: localAsset(`sprites/${prefix}_knockdown.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-24x32",
      packId,
      tags: ["fighter", "knockdown", "legacy"],
      frameConfig: { frameWidth: 24, frameHeight: 32 },
    },
    {
      key: `${prefix}_getup`,
      path: localAsset(`sprites/${prefix}_getup.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16x32",
      packId,
      tags: ["fighter", "getup", "legacy"],
      frameConfig: { frameWidth: 16, frameHeight: 32 },
    },
  ];
}

const LEGACY_COMMON: AssetManifestEntry[] = [
  {
    key: "street_sheet",
    path: localAsset("sprites/street_sheet.png"),
    type: "image",
    role: "tileset",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-tile-set-market-street-sms",
    paletteProfile: "market-street-sms",
    scaleProfile: "bg-native",
    packId: "legacy_sms",
    tags: ["stage", "legacy"],
  },
  {
    key: "street_tileset",
    path: localAsset("sprites/street_tileset.png"),
    type: "image",
    role: "tileset",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-tile-set-market-street-sms",
    paletteProfile: "market-street-sms",
    scaleProfile: "tile-16x16",
    packId: "legacy_sms",
    tags: ["stage", "legacy"],
  },
  {
    key: "street_props",
    path: localAsset("sprites/street_props.png"),
    type: "image",
    role: "prop",
    critical: false,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-tile-set-market-street-sms",
    paletteProfile: "market-street-sms",
    scaleProfile: "prop-native",
    packId: "legacy_sms",
    tags: ["prop", "legacy"],
  },
  {
    key: "police_car_sheet",
    path: localAsset("sprites/police_car_sheet.png"),
    type: "image",
    role: "prop",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/police-car-sprite-sheet-sms",
    paletteProfile: "sms-nocturno-neon",
    scaleProfile: "prop-native",
    packId: "legacy_sms",
    tags: ["prop", "legacy"],
  },
  {
    key: "city_far",
    path: localAsset("backgrounds/city_far.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Quintus",
    license: "CC0",
    url: "https://opengameart.org/content/city-scrollable-background-pixel-art",
    paletteProfile: "blue-night",
    scaleProfile: "bg-wide",
    packId: "legacy_sms",
    tags: ["background", "legacy"],
  },
  {
    key: "city_mid",
    path: localAsset("backgrounds/city_mid.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Quintus",
    license: "CC0",
    url: "https://opengameart.org/content/city-scrollable-background-pixel-art",
    paletteProfile: "blue-night",
    scaleProfile: "bg-wide",
    packId: "legacy_sms",
    tags: ["background", "legacy"],
  },
  {
    key: "city_close",
    path: localAsset("backgrounds/city_close.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Quintus",
    license: "CC0",
    url: "https://opengameart.org/content/city-scrollable-background-pixel-art",
    paletteProfile: "blue-night",
    scaleProfile: "bg-wide",
    packId: "legacy_sms",
    tags: ["background", "legacy"],
  },
  {
    key: "portrait_boxeador",
    path: localAsset("sprites/player_punch1.png"),
    type: "image",
    role: "ui",
    critical: true,
    pixelScale: 3,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-character-renegade-sms",
    paletteProfile: "sms-nocturno-neon",
    scaleProfile: "portrait-legacy",
    packId: "legacy_sms",
    tags: ["ui", "portrait", "legacy"],
  },
  {
    key: "portrait_veloz",
    path: localAsset("sprites/player_kick1.png"),
    type: "image",
    role: "ui",
    critical: true,
    pixelScale: 3,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-character-renegade-sms",
    paletteProfile: "sms-nocturno-neon",
    scaleProfile: "portrait-legacy",
    packId: "legacy_sms",
    tags: ["ui", "portrait", "legacy"],
  },
  {
    key: "portrait_tecnico",
    path: localAsset("sprites/player_punch2.png"),
    type: "image",
    role: "ui",
    critical: true,
    pixelScale: 3,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-character-renegade-sms",
    paletteProfile: "sms-nocturno-neon",
    scaleProfile: "portrait-legacy",
    packId: "legacy_sms",
    tags: ["ui", "portrait", "legacy"],
  },
  {
    key: "theme_a",
    path: localAsset("audio/theme_spacyloop.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "bart",
    license: "CC0",
    url: "https://opengameart.org/content/spacyloop",
    paletteProfile: "arcade-90s",
    scaleProfile: "audio-loop",
    packId: "legacy_sms",
    tags: ["audio", "theme"],
  },
  {
    key: "theme_b",
    path: localAsset("audio/theme_emptycity.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Binarpilot",
    license: "CC0",
    url: "https://opengameart.org/content/empty-city",
    paletteProfile: "arcade-90s",
    scaleProfile: "audio-loop",
    packId: "legacy_sms",
    tags: ["audio", "theme"],
  },
  {
    key: "sfx_hit",
    path: localAsset("audio/sfx_hit.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Devlos",
    license: "CC-BY",
    url: "https://opengameart.org/content/punch-sound-effect",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "legacy_sms",
    tags: ["audio", "sfx", "hit"],
  },
  {
    key: "sfx_hit_alt",
    path: localAsset("audio/sfx_hit.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Devlos",
    license: "CC-BY",
    url: "https://opengameart.org/content/punch-sound-effect",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "legacy_sms",
    tags: ["audio", "sfx", "hit"],
  },
  {
    key: "sfx_jump",
    path: localAsset("audio/sfx_jump.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC-BY",
    url: "https://opengameart.org/content/jump-and-run-8-bit",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "legacy_sms",
    tags: ["audio", "sfx", "jump"],
  },
  {
    key: "sfx_special",
    path: localAsset("audio/sfx_special.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "legacy_sms",
    tags: ["audio", "sfx", "special"],
  },
  {
    key: "sfx_knockdown",
    path: localAsset("audio/sfx_knockdown.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "legacy_sms",
    tags: ["audio", "sfx", "knockdown"],
  },
  {
    key: "sfx_break",
    path: localAsset("audio/sfx_knockdown.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "legacy_sms",
    tags: ["audio", "sfx", "break"],
  },
  {
    key: "sfx_ui",
    path: localAsset("audio/sfx_special.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
    packId: "legacy_sms",
    tags: ["audio", "sfx", "ui"],
  },
];

export const legacyManifest: AssetManifestEntry[] = [
  ...createLegacyCharacterSet("player", "https://opengameart.org/content/brawler-asset-character-renegade-sms"),
  ...createLegacyCharacterSet("enemy", "https://opengameart.org/content/ranger-character-sprite-sheets-sms"),
  ...LEGACY_COMMON,
];
