import { derivedAssetKeys } from "./derivedTextureCrops";
export { derivedAssetKeys };

export type AssetType = "image" | "spritesheet" | "audio";
export type AssetRole = "character" | "tileset" | "prop" | "background" | "audio";

export interface AssetManifestEntry {
  key: string;
  path: string;
  type: AssetType;
  role: AssetRole;
  critical: boolean;
  pixelScale: 1 | 2 | 3;
  source: "OpenGameArt" | "Kenney" | "itch.io" | "Freesound" | "Pixabay";
  author: string;
  license: "CC0" | "CC-BY";
  url: string;
  paletteProfile: string;
  scaleProfile: string;
  frameConfig?: {
    frameWidth: number;
    frameHeight: number;
  };
}

function localAsset(path: string): string {
  return `/assets/external/${path}`;
}

function createCharacterSet(
  prefix: "player" | "enemy",
  author: string,
  url: string,
  paletteProfile: string,
): AssetManifestEntry[] {
  return [
    {
      key: `${prefix}_idle_strip4`,
      path: localAsset(`sprites/${prefix}_idle_strip4.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
      frameConfig: { frameWidth: 16, frameHeight: 32 },
    },
    {
      key: `${prefix}_walk_strip4`,
      path: localAsset(`sprites/${prefix}_walk_strip4.png`),
      type: "spritesheet",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
      frameConfig: { frameWidth: 16, frameHeight: 32 },
    },
    {
      key: `${prefix}_punch1`,
      path: localAsset(`sprites/${prefix}_punch1.png`),
      type: "image",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
    },
    {
      key: `${prefix}_punch2`,
      path: localAsset(`sprites/${prefix}_punch2.png`),
      type: "image",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
    },
    {
      key: `${prefix}_kick1`,
      path: localAsset(`sprites/${prefix}_kick1.png`),
      type: "image",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
    },
    {
      key: `${prefix}_kick2`,
      path: localAsset(`sprites/${prefix}_kick2.png`),
      type: "image",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
    },
    {
      key: `${prefix}_hurt`,
      path: localAsset(`sprites/${prefix}_hurt.png`),
      type: "image",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
    },
    {
      key: `${prefix}_knockdown`,
      path: localAsset(`sprites/${prefix}_knockdown.png`),
      type: "image",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
    },
    {
      key: `${prefix}_getup`,
      path: localAsset(`sprites/${prefix}_getup.png`),
      type: "image",
      role: "character",
      critical: true,
      pixelScale: 3,
      source: "OpenGameArt",
      author,
      license: "CC0",
      url,
      paletteProfile,
      scaleProfile: "character-16px-x3",
    },
  ];
}

export const assetManifest: AssetManifestEntry[] = [
  ...createCharacterSet(
    "player",
    "chasersgaming",
    "https://opengameart.org/content/brawler-asset-character-renegade-sms",
    "sms-nocturno-neon",
  ),
  ...createCharacterSet(
    "enemy",
    "chasersgaming",
    "https://opengameart.org/content/ranger-character-sprite-sheets-sms",
    "sms-nocturno-neon",
  ),
  {
    key: "street_sheet",
    path: localAsset("sprites/street_sheet.png"),
    type: "image",
    role: "tileset",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-tile-set-market-street-sms",
    paletteProfile: "market-street-sms",
    scaleProfile: "bg-native",
  },
  {
    key: "street_tileset",
    path: localAsset("sprites/street_tileset.png"),
    type: "image",
    role: "tileset",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-tile-set-market-street-sms",
    paletteProfile: "market-street-sms",
    scaleProfile: "tile-16x16",
  },
  {
    key: "street_props",
    path: localAsset("sprites/street_props.png"),
    type: "image",
    role: "prop",
    critical: false,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/brawler-asset-tile-set-market-street-sms",
    paletteProfile: "market-street-sms",
    scaleProfile: "prop-native",
  },
  {
    key: "police_car_sheet",
    path: localAsset("sprites/police_car_sheet.png"),
    type: "image",
    role: "prop",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "chasersgaming",
    license: "CC0",
    url: "https://opengameart.org/content/police-car-sprite-sheet-sms",
    paletteProfile: "sms-nocturno-neon",
    scaleProfile: "prop-native",
  },
  {
    key: "city_far",
    path: localAsset("backgrounds/city_far.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Quintus",
    license: "CC0",
    url: "https://opengameart.org/content/city-scrollable-background-pixel-art",
    paletteProfile: "blue-night",
    scaleProfile: "bg-wide",
  },
  {
    key: "city_mid",
    path: localAsset("backgrounds/city_mid.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Quintus",
    license: "CC0",
    url: "https://opengameart.org/content/city-scrollable-background-pixel-art",
    paletteProfile: "blue-night",
    scaleProfile: "bg-wide",
  },
  {
    key: "city_close",
    path: localAsset("backgrounds/city_close.png"),
    type: "image",
    role: "background",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Quintus",
    license: "CC0",
    url: "https://opengameart.org/content/city-scrollable-background-pixel-art",
    paletteProfile: "blue-night",
    scaleProfile: "bg-wide",
  },
  {
    key: "theme_a",
    path: localAsset("audio/theme_spacyloop.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "bart",
    license: "CC0",
    url: "https://opengameart.org/content/spacyloop",
    paletteProfile: "arcade-90s",
    scaleProfile: "audio-loop",
  },
  {
    key: "theme_b",
    path: localAsset("audio/theme_emptycity.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Binarpilot",
    license: "CC0",
    url: "https://opengameart.org/content/empty-city",
    paletteProfile: "arcade-90s",
    scaleProfile: "audio-loop",
  },
  {
    key: "sfx_hit",
    path: localAsset("audio/sfx_hit.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "Devlos",
    license: "CC-BY",
    url: "https://opengameart.org/content/punch-sound-effect",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
  },
  {
    key: "sfx_jump",
    path: localAsset("audio/sfx_jump.ogg"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC-BY",
    url: "https://opengameart.org/content/jump-and-run-8-bit",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
  },
  {
    key: "sfx_special",
    path: localAsset("audio/sfx_special.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
  },
  {
    key: "sfx_knockdown",
    path: localAsset("audio/sfx_knockdown.wav"),
    type: "audio",
    role: "audio",
    critical: true,
    pixelScale: 1,
    source: "OpenGameArt",
    author: "qubodup",
    license: "CC0",
    url: "https://opengameart.org/content/95-game-sounds",
    paletteProfile: "impact-arcade",
    scaleProfile: "audio-sfx",
  },
];

export const requiredAssetKeys = [
  ...assetManifest.filter((entry) => entry.critical).map((entry) => entry.key),
  ...derivedAssetKeys,
  "utility-white",
] as const;
