export interface DerivedTextureCrop {
  sourceKey: string;
  targetKey: string;
  sx: number;
  sy: number;
  width: number;
  height: number;
}

export const derivedTextureCrops: DerivedTextureCrop[] = [
  {
    sourceKey: "street_sheet",
    targetKey: "street_clean_tileset",
    sx: 1792,
    sy: 80,
    width: 1280,
    height: 768,
  },
  {
    sourceKey: "street_sheet",
    targetKey: "street_market_tileset",
    sx: 128,
    sy: 80,
    width: 1280,
    height: 768,
  },
  {
    sourceKey: "street_sheet",
    targetKey: "street_metro_tileset",
    sx: 832,
    sy: 80,
    width: 1280,
    height: 768,
  },
  {
    sourceKey: "street_sheet",
    targetKey: "street_playa_tileset",
    sx: 1408,
    sy: 80,
    width: 1280,
    height: 768,
  },
  {
    sourceKey: "street_sheet",
    targetKey: "street_puerto_tileset",
    sx: 2144,
    sy: 80,
    width: 1280,
    height: 768,
  },
  {
    sourceKey: "street_props",
    targetKey: "prop_booth_front",
    sx: 0,
    sy: 512,
    width: 256,
    height: 384,
  },
  {
    sourceKey: "street_props",
    targetKey: "prop_dumpster_open",
    sx: 0,
    sy: 192,
    width: 384,
    height: 320,
  },
  {
    sourceKey: "street_props",
    targetKey: "prop_container_pair",
    sx: 512,
    sy: 192,
    width: 384,
    height: 320,
  },
  {
    sourceKey: "street_props",
    targetKey: "prop_container",
    sx: 640,
    sy: 192,
    width: 256,
    height: 320,
  },
  {
    sourceKey: "street_props",
    targetKey: "prop_container_green",
    sx: 640,
    sy: 192,
    width: 128,
    height: 320,
  },
  {
    sourceKey: "street_props",
    targetKey: "prop_crate",
    sx: 0,
    sy: 0,
    width: 384,
    height: 512,
  },
  {
    sourceKey: "oga_city_tiles",
    targetKey: "prop_street_tree",
    sx: 0,
    sy: 120,
    width: 40,
    height: 40,
  },
  {
    sourceKey: "oga_city_tiles",
    targetKey: "prop_barricade_small",
    sx: 40,
    sy: 140,
    width: 40,
    height: 20,
  },
  {
    sourceKey: "oga_city_tiles",
    targetKey: "prop_sign_post",
    sx: 80,
    sy: 120,
    width: 20,
    height: 60,
  },
  {
    sourceKey: "oga_city_tiles",
    targetKey: "prop_trash_bin_small",
    sx: 100,
    sy: 100,
    width: 24,
    height: 24,
  },
  {
    sourceKey: "oga_city_tiles",
    targetKey: "prop_caution_cone",
    sx: 140,
    sy: 100,
    width: 20,
    height: 20,
  },
  {
    sourceKey: "city_far",
    targetKey: "city_far_market_band",
    sx: 384,
    sy: 600,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_far",
    targetKey: "city_far_metro_band",
    sx: 2304,
    sy: 600,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_far",
    targetKey: "city_far_playa_band",
    sx: 4352,
    sy: 600,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_far",
    targetKey: "city_far_puerto_band",
    sx: 6848,
    sy: 600,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_far",
    targetKey: "city_far_band",
    sx: 6720,
    sy: 600,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_mid",
    targetKey: "city_mid_market_band",
    sx: 512,
    sy: 720,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_mid",
    targetKey: "city_mid_metro_band",
    sx: 2560,
    sy: 720,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_mid",
    targetKey: "city_mid_playa_band",
    sx: 4608,
    sy: 720,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_mid",
    targetKey: "city_mid_puerto_band",
    sx: 6784,
    sy: 720,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_mid",
    targetKey: "city_mid_band",
    sx: 1728,
    sy: 720,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_close",
    targetKey: "city_close_market_band",
    sx: 896,
    sy: 840,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_close",
    targetKey: "city_close_metro_band",
    sx: 2816,
    sy: 840,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_close",
    targetKey: "city_close_playa_band",
    sx: 4864,
    sy: 840,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_close",
    targetKey: "city_close_puerto_band",
    sx: 6848,
    sy: 840,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "city_close",
    targetKey: "city_close_band",
    sx: 6656,
    sy: 840,
    width: 2048,
    height: 240,
  },
  {
    sourceKey: "street_tileset",
    targetKey: "hud_frame",
    sx: 0,
    sy: 0,
    width: 128,
    height: 128,
  },
  {
    sourceKey: "street_tileset",
    targetKey: "ui_btn",
    sx: 128,
    sy: 128,
    width: 128,
    height: 128,
  },
  {
    sourceKey: "street_tileset",
    targetKey: "hit_spark",
    sx: 640,
    sy: 512,
    width: 128,
    height: 128,
  },
];

export const derivedAssetKeys = derivedTextureCrops.map((entry) => entry.targetKey);
